#!/bin/bash

# Password for bandit1 is: boJ9jbbUNNfktd78OOpsqOltutMc3MY1
scp -P 2220 bandit1@bandit.labs.overthewire.org:/home/bandit1/- flag.txt
cat flag.txt && rm flag.txt

# Flag for next level is: boJ9jbbUNNfktd78OOpsqOltutMc3MY1 
